# Generated by Django 5.2.4 on 2025-08-05 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workouttemplate_templateexercise_templateset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutTemplate',
            new_name='TemplateWorkout',
        ),
    ]
