# Generated by Django 5.2.4 on 2025-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_workouttemplate_templateworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight_change_preference',
            field=models.CharField(choices=[('increase', 'Increase Weight'), ('decrease', 'Decrease Weight'), ('same', 'Maintain Weight')], default='same', help_text='User preference for weight change on this exercise', max_length=8),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
