# Generated by Django 5.2.4 on 2025-10-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercise_weight_change_preference_and_more'),
    ]

    operations = [
        # Add the unique constraints that are defined in the model Meta classes
        # These should be created automatically, but we'll ensure they exist
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise_number'), name='unique_exercise_number_per_workout'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('exercise', 'set_number'), name='unique_set_number_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('user', 'workout_number'), name='unique_workout_number_per_user'),
        ),
    ]
